version: "3.9"
services:
  hello-world:
    build: functions/hello-world/
    image: hello-world:latest
    container_name: hello-world    
    working_dir: /var/task
    ports:
      - "9000:8080"
      - "6900:6900"
    volumes:
      - ./functions/hello-world:/var/task
  string-reverser:
    build: functions/string-reverser/
    image: string-reverser:latest
    container_name: string-reverser    
    working_dir: /var/task
    ports:
      - "9001:8080"
      - "6900:6900"
    volumes:
      - ./functions/string-reverser:/var/task      