version: "3.9"
services:
  hello_world:
    build: functions/hello_world/
    image: hello_world:latest
    container_name: hello_world    
    working_dir: /var/task
    ports:
      - "9000:8080"
      - "6900:6900"
    volumes:
      - ./functions/hello_world:/var/task
  string_reverser:
    build: functions/string_reverser/
    image: string_reverser:latest
    container_name: string_reverser    
    working_dir: /var/task
    ports:
      - "9001:8080"
      - "6900:6900"
    volumes:
      - ./lib/:/var/task/lib
      - ./tests/functions/string_reverser:/var/task/tests/functions/string_reverser
      - ./functions/string_reverser:/var/task/functions/string_reverser     
  write_dynamo:
    build: functions/write_dynamo/
    image: write_dynamo:latest
    container_name: write_dynamo    
    working_dir: /var/task
    env_file:
      - functions/write_dynamo/.env
    ports:
      - "9002:8080"
      - "6900:6900"
    volumes:
      - ./lib/:/var/task/lib
      - ./tests/functions/write_dynamo:/var/task/tests/functions/write_dynamo
      - ./functions/write_dynamo:/var/task/functions/write_dynamo   